# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Moya-PromiseKit-Service' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Moya-PromiseKit-Service
    pod "Alamofire"
    pod "PromiseKit/Alamofire"
    pod "PromiseKit"
    pod "Moya"
  target 'Moya-PromiseKit-ServiceTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
