# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoyaPromiseExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  source 'https://github.com/CocoaPods/Specs.git'
  source 'https://github.com/Can-Sahin/MoyaPromise'
  pod “MoyaPromise”
#  pod "Alamofire"
#  pod "PromiseKit/Alamofire"
#  pod "PromiseKit"
#  pod "Moya"
end
