# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoyaPromiseExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoyaPromiseExample
    pod "Alamofire"
    pod "PromiseKit/Alamofire"
    pod "PromiseKit"
    pod "Moya"

end
