# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoyaPromise' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for MoyaPromise
  pod “Alamofire”
  pod “PromiseKit/Alamofire”
  pod “PromiseKit”
  pod “Moya”

  target 'MoyaPromiseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
